
language: node_js
node_js:
 - "node"

install:
- npm install

deploy:
  skip_cleanup: true
  edge: true
  provider: heroku
  api-key: 
    api-key: $HEROKU_API_KEY
  app: projetonodees
  on:
    branch: master
